name = "OliveHighlighters"
uuid = "f769160f-f39a-4920-b1de-ba699e2d8893"
authors = ["emmac "]
version = "0.1.3"

[deps]
ToolipsServables = "bf3a9e68-ca66-4981-8178-9d71c4f8abaa"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
Unicode = "1.11.0"
ToolipsServables = "0.2.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
